### ISSUE TITLE
page command is throwing a syntax error

### ISSUE THREAD

**Issue by rrakman** [haguezoum/amadil#1]
routes.js:18
export default routes;
^^^^^^
SyntaxError: Unexpected token 'export'

Node.js v18.19.0

**Comment by haguezoum** [comment]
Hello, @rrakman ! Thank you for using **Amadil CLI**. This problem is probably related to **sudo permissions.** Please execute the following command in your terminal:
```bash
cd ~ 
sudo chown -R 501:20 : .npm 
```
